name: "Test"

on:
  workflow_dispatch:
  schedule:
    - cron: "18 18 * * 1,3,5"
  push:
    branches: [master]
    paths:
      - ".github/workflows/test.yaml"
      - "dist/**"
      - "src/**"
      - "package*.json"
      - "requirements*.txt"
      - "action.yml"
  pull_request:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          url: https://httpbin.org/post
          #url: http://192.168.1.25:8080/post
          #insecure: true
          #data: '{"key": "value"}'
          data: |
            key: value
          params: |
            param1: value1
          file: event.json
          filename: not-event.json

      - name: "Verify Outputs"
        if: ${{ !github.event.act }}
        run: |
          echo 'status: ${{ steps.test.outputs.status }}'
          echo 'headers: ${{ steps.test.outputs.headers }}'
          echo 'data: ${{ steps.test.outputs.data }}'
          if [ '${{ fromJson(steps.test.outputs.data).data }}' != '{"key":"value"}' ];then
            echo "Output Invalid"
            exit 1
          fi

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
